#!/usr/bin/env bash

cat <<EOF > /root/.my.cnf
[client]
user = root
password = secret
host = localhost
EOF

cp /root/.my.cnf /home/vagrant/.my.cnf

db_name=$1;
db_user=$2;
db_password=$3;

mysql -e "CREATE DATABASE IF NOT EXISTS \`$db_name\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci";
mysql -e "GRANT ALL ON \`$db_name\`.* TO '$db_user'@'0.0.0.0' IDENTIFIED BY '$db_password';"
mysql -e "GRANT ALL ON \`$db_name\`.* TO '$db_user'@'%' IDENTIFIED BY '$db_password';"
mysql -e 'FLUSH PRIVILEGES;'