#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

version="${1:-3.9.1}"
download_file="selenium-server-standalone-$version.jar"
bin_path='/usr/local/bin'
file='selenium-server-standalone.jar'

# Install Selenium Server Standalone
if [[ -f "$bin_path/$file" ]]
then
    echo 'Selenium Server Standalone already installed'
else
    wget -N "http://selenium-release.storage.googleapis.com/$(grep -Eo '^[0-9]+\.[0-9]+' <<< "$version")/$download_file" > /dev/null 2>&1
    mv -f "$download_file" "$bin_path/$file"
fi