#!/usr/bin/env bash

export DEBIAN_FRONTEND=noninteractive

version=$1
current_version=$(update-alternatives --get-selections | grep 'php' | awk '{print$3}' | grep -Eo '[0-9]\.*[0-9]*')
ubuntu=$(lsb_release -r | awk '{print $2}')
ubuntu_major=$(echo "$ubuntu" | awk -F. '{print $1}')

if [[ "$version" = "$current_version" ]]
then
    echo "PHP CLI already using version $version"
    exit 0
fi

if [[ "$ubuntu_major" > '14' && "$version" < '5.6' ]]
then
    echo "PHP $version not supported on Ubuntu $ubuntu"
    exit 1
fi

update-alternatives --set php "/usr/bin/php$version" > /dev/null